# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import siphon.web.apps.permissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0006_app_facebook_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('team-member', 'Team member')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('invite_email', models.EmailField(max_length=254, unique=True)),
                ('invite_code', models.CharField(default=siphon.web.apps.permissions.models.make_invite_code, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('aliased_app', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_permission', to='apps.App')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='apps.App')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
