# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='permission_type',
            field=models.CharField(choices=[('team-member', 'Team member'), ('beta-tester', 'Beta tester')], max_length=20),
        ),
    ]
