# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargebeeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('plan_id', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('interval', models.CharField(choices=[('monthly', 'Billed monthly'), ('yearly', 'Billed yearly')], max_length=20)),
                ('seats', models.PositiveIntegerField(help_text='Number of developer seats.')),
                ('monthly_active_users', models.PositiveIntegerField(help_text='A value of zero value means unlimited.')),
                ('max_app_size', models.PositiveIntegerField(help_text='Maximum app size in bytes. A value of zero means unlimited.')),
                ('priority_support', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('chargebee_id', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
