# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='beta_tester_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='team_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
