# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([]),
        ),
    ]
