# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20160302_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
