# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20160613_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('height', models.IntegerField(choices=[(512, 512), (1024, 1024)])),
                ('width', models.IntegerField(choices=[(512, 512), (1024, 1024)])),
                ('image_format', models.CharField(choices=[('png', 'PNG')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='app_store_language',
            field=models.CharField(blank=True, choices=[('en-au', 'en-AU'), ('pt-br', 'pt-BR'), ('en-ca', 'en-CA'), ('fr-ca', 'fr-CA'), ('da-dk', 'da-DK'), ('en', 'en'), ('fi-fi', 'fi-FI'), ('fr-fr', 'fr-FR'), ('de-de', 'de-DE'), ('el-gr', 'el-GR'), ('id', 'id'), ('it-it', 'it-IT'), ('ja-jp', 'ja-JP'), ('ko-kr', 'ko-KR'), ('ms', 'ms'), ('es-mx', 'es-MX'), ('no-no', 'no-NO'), ('pt-pt', 'pt-PT'), ('ru-ru', 'ru-RU'), ('es-es', 'es-ES'), ('sv-se', 'sv-SE'), ('th', 'th'), ('zh-hans', 'zh-Hans'), ('zh-tw', 'zh-TW'), ('tr-tr', 'tr-TR'), ('en-gb', 'en-GB'), ('vi', 'vi')], max_length=7),
        ),
        migrations.AddField(
            model_name='app',
            name='app_store_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='app',
            name='play_store_language',
            field=models.CharField(blank=True, choices=[('af', 'Af'), ('am', 'am'), ('ar', 'ar'), ('az-az', 'az-AZ'), ('be', 'be'), ('bn-bd', 'bn-BD'), ('bg', 'bg'), ('ca', 'ca'), ('cs-cz', 'cs-CZ'), ('da-dk', 'da-DK'), ('de-de', 'de-DE'), ('el-gr', 'el-GR'), ('en-au', 'en-AU'), ('en-gb', 'en-GB'), ('en-in', 'en-IN'), ('en-us', 'en-US'), ('es-419', 'es-419'), ('es-es', 'es-ES'), ('es-us', 'es-US'), ('et', 'et'), ('eu-es', 'eu-ES'), ('fa', 'fa'), ('fi-fi', 'fi-FI'), ('fr-ca', 'fr-CA'), ('fr-fr', 'fr-FR'), ('gl-es', 'gl-ES'), ('hi-in', 'hi-IN'), ('hr', 'hr'), ('hu-hu', 'hu-HU'), ('hy-am', 'hy-AM'), ('id', 'id'), ('is-is', 'is-IS'), ('it-it', 'it-IT'), ('iw-il', 'iw-IL'), ('ja-jp', 'ja-JP'), ('ka-ge', 'ka-GE'), ('km-kh', 'km-KH'), ('ko-kr', 'ko-KR'), ('kn-in', 'kn-IN'), ('ky-kg', 'ky-KG'), ('lo-la', 'lo-LA'), ('lt', 'lt'), ('lv', 'lv'), ('mk-mk', 'mk-MK'), ('ml-in', 'ml-IN'), ('mn-mn', 'mn-MN'), ('mr-in', 'mr-IN'), ('ms', 'ms'), ('my-mm', 'my-MM'), ('ne-np', 'ne-NP'), ('nl-nl', 'nl-NL'), ('no-no', 'no-NO'), ('pl-pl', 'pl-PL'), ('pt-br', 'pt-BR'), ('pt-pt', 'pt-PT'), ('rm', 'rm'), ('ro', 'ro'), ('ru-ru', 'ru-RU'), ('si-lk', 'si-LK'), ('sk', 'sk'), ('sl', 'sl'), ('sr', 'sr'), ('sv-se', 'sv-SE'), ('sw', 'sw'), ('ta-in', 'ta-IN'), ('te-in', 'te-IN'), ('th', 'th'), ('fil', 'fil'), ('tr-tr', 'tr-TR'), ('uk', 'uk'), ('vi', 'vi'), ('zh-cn', 'zh-CN'), ('zh-tw', 'zh-TW'), ('zu', 'zu')], max_length=7),
        ),
        migrations.AddField(
            model_name='app',
            name='play_store_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appicon',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='apps.App'),
        ),
    ]
