# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='display_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
