# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:29
from __future__ import unicode_literals

from django.db import migrations

def set_display_names(apps, schema_editor):
    Submission = apps.get_model('submissions', 'Submission')
    for sub in Submission.objects.all():
        sub.display_name = sub.app.display_name
        sub.save()

class Migration(migrations.Migration):
    dependencies = [
        ('submissions', '0004_submission_display_name'),
    ]

    operations = [
        migrations.RunPython(set_display_names),
    ]
