# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20160224_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='display_name',
            field=models.CharField(max_length=32),
        ),
    ]
