# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20160224_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
