# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_is_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('released', 'Released')], max_length=20),
        ),
    ]
