# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20160224_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='platform_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='platform_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
