# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20160420_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('awaiting_release', 'Awaiting Release'), ('released', 'Released')], max_length=20),
        ),
    ]
